INSERT INTO job_region (name) VALUES ('Northland');
INSERT INTO job_region (name) VALUES ('Auckland');
INSERT INTO job_region (name) VALUES ('Waikato');
INSERT INTO job_region (name) VALUES ('Bay of Plenty');
INSERT INTO job_region (name) VALUES ('Gisborne');
INSERT INTO job_region (name) VALUES ('Hawke\'s Bay');
INSERT INTO job_region (name) VALUES ('Taranaki');
INSERT INTO job_region (name) VALUES ('Manuwatu-Wanganui');
INSERT INTO job_region (name) VALUES ('Wellington');
INSERT INTO job_region (name) VALUES ('Tasman');
INSERT INTO job_region (name) VALUES ('Nelson');
INSERT INTO job_region (name) VALUES ('Marlborough');
INSERT INTO job_region (name) VALUES ('West Coast');
INSERT INTO job_region (name) VALUES ('Canterbury');
INSERT INTO job_region (name) VALUES ('Otago');
INSERT INTO job_region (name) VALUES ('Southland');
