INSERT INTO job_city (name, region_id) VALUES ('Whangarei', 1);
INSERT INTO job_city (name, region_id) VALUES ('Kaitaia', 1);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Northland', 1);
INSERT INTO job_city (name, region_id) VALUES ('Auckland Central', 2);
INSERT INTO job_city (name, region_id) VALUES ('Manakau\\East Auckland', 2);
INSERT INTO job_city (name, region_id) VALUES ('Papakura\\Franklin', 2);
INSERT INTO job_city (name, region_id) VALUES ('Rodney\\North Shore', 2);
INSERT INTO job_city (name, region_id) VALUES ('Waitakere\\West Auckland', 2);
INSERT INTO job_city (name, region_id) VALUES ('Hamilton', 3);
INSERT INTO job_city (name, region_id) VALUES ('Taupo', 3);
INSERT INTO job_city (name, region_id) VALUES ('Theme\\Coromandel', 3);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Waikato', 3);
INSERT INTO job_city (name, region_id) VALUES ('Rotorua', 4);
INSERT INTO job_city (name, region_id) VALUES ('Tauranga', 4);
INSERT INTO job_city (name, region_id) VALUES ('Rest of BOP', 4);
INSERT INTO job_city (name, region_id) VALUES ('Gisborne', 5);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Gisborne', 5);
INSERT INTO job_city (name, region_id) VALUES ('Hastings', 6);
INSERT INTO job_city (name, region_id) VALUES ('Napier', 6);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Hawke\'s Bay', 6);
INSERT INTO job_city (name, region_id) VALUES ('New Plymouth', 7);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Taranaki', 7);
INSERT INTO job_city (name, region_id) VALUES ('Palmerston North', 8);
INSERT INTO job_city (name, region_id) VALUES ('Wanganui', 8);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Manawatu-Wanganui', 8);
INSERT INTO job_city (name, region_id) VALUES ('Wellington Central', 9);
INSERT INTO job_city (name, region_id) VALUES ('Hutt Valley', 9);
INSERT INTO job_city (name, region_id) VALUES ('Porirua\\Kapiti Coast', 9);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Wellington', 9);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Tasman', 10);
INSERT INTO job_city (name, region_id) VALUES ('Nelson', 11);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Nelson', 11);
INSERT INTO job_city (name, region_id) VALUES ('Blenheim', 12);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Marlborough', 12);
INSERT INTO job_city (name, region_id) VALUES ('Greymouth', 13);
INSERT INTO job_city (name, region_id) VALUES ('Rest of West Coast', 13);
INSERT INTO job_city (name, region_id) VALUES ('Christchurch', 14);
INSERT INTO job_city (name, region_id) VALUES ('North Canterbury', 14);
INSERT INTO job_city (name, region_id) VALUES ('Timaru\\South Canterbury', 14);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Canterbury', 14);
INSERT INTO job_city (name, region_id) VALUES ('Dunedin', 15);
INSERT INTO job_city (name, region_id) VALUES ('Queenstown', 15);
INSERT INTO job_city (name, region_id) VALUES ('Wanaka', 15);
INSERT INTO job_city (name, region_id) VALUES ('Alexandra', 15);
INSERT INTO job_city (name, region_id) VALUES ('Oamaru', 15);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Otago', 15);
INSERT INTO job_city (name, region_id) VALUES ('Invercargill', 16);
INSERT INTO job_city (name, region_id) VALUES ('Rest of Southland', 16);
